# Generated by Django 4.2.3 on 2023-12-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_conlog_subsr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ip',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='conlog',
            name='pinfo',
            field=models.CharField(max_length=1000),
        )
    ]
